import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState, useMemo } from 'react';
export const SwipeFileList = ({ cards, onDelete, onDuplicate, }) => {
    const [search, setSearch] = useState('');
    const [typeFilter, setTypeFilter] = useState('all');
    const [expandedCardId, setExpandedCardId] = useState(null);
    const filteredCards = useMemo(() => {
        return cards.filter((card) => {
            const matchesSearch = card.title.toLowerCase().includes(search.toLowerCase()) ||
                (card.content && card.content.toLowerCase().includes(search.toLowerCase())) ||
                (card.transcript && card.transcript.toLowerCase().includes(search.toLowerCase()));
            const matchesType = typeFilter === 'all' || card.type === typeFilter;
            return matchesSearch && matchesType;
        });
    }, [cards, search, typeFilter]);
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "space-y-3", children: [_jsx("input", { type: "text", placeholder: "Search cards...", value: search, onChange: (e) => setSearch(e.target.value), className: "w-full px-4 py-2 bg-surface border border-border rounded text-light placeholder-border focus:outline-none focus:border-accent-primary" }), _jsx("div", { className: "flex gap-2 flex-wrap", children: ['all', 'youtube', 'text', 'script'].map((type) => (_jsx("button", { onClick: () => setTypeFilter(type), className: `px-3 py-1 rounded text-sm transition-colors ${typeFilter === type
                                ? 'bg-accent-primary text-dark'
                                : 'bg-surface border border-border text-light hover:border-accent-primary'}`, children: type === 'all' ? 'All' : type.charAt(0).toUpperCase() + type.slice(1) }, type))) })] }), _jsx("div", { className: "space-y-2", children: filteredCards.length === 0 ? (_jsx("div", { className: "text-center py-8 text-border", children: _jsx("p", { children: "No cards found" }) })) : (filteredCards.map((card) => (_jsxs("div", { className: "bg-surface border border-border rounded overflow-hidden", children: [_jsxs("div", { onClick: () => setExpandedCardId(expandedCardId === card.id ? null : card.id), className: "p-4 cursor-pointer hover:bg-border transition-colors flex items-start justify-between gap-4", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "px-2 py-0.5 bg-border rounded text-xs text-light capitalize", children: card.type }), _jsx("h4", { className: "text-light font-semibold flex-1", children: card.title })] }), _jsx("p", { className: "text-xs text-border line-clamp-1", children: card.type === 'youtube' && card.transcript
                                                ? card.transcript.substring(0, 100)
                                                : card.content?.substring(0, 100) })] }), _jsx("span", { className: "text-border", children: expandedCardId === card.id ? '▼' : '▶' })] }), expandedCardId === card.id && (_jsxs("div", { className: "border-t border-border px-4 py-4 bg-dark", children: [card.type === 'youtube' && (_jsxs(_Fragment, { children: [card.thumbnail_url && (_jsx("div", { className: "mb-4 w-full h-32 rounded overflow-hidden", children: _jsx("img", { src: card.thumbnail_url, alt: card.title, className: "w-full h-full object-cover" }) })), card.youtube_url && (_jsx("a", { href: card.youtube_url, target: "_blank", rel: "noopener noreferrer", className: "text-accent-primary hover:text-accent-hover text-sm block mb-3", children: "Watch on YouTube \u2192" }))] })), _jsx("div", { className: "text-light text-sm max-h-48 overflow-y-auto whitespace-pre-wrap mb-4", children: card.type === 'youtube' ? card.transcript : card.content }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: () => onDuplicate(card.id), className: "px-3 py-1 bg-accent-primary hover:bg-accent-hover text-dark rounded text-sm font-medium transition-colors", children: "Duplicate" }), _jsx("button", { onClick: () => onDelete(card.id), className: "px-3 py-1 bg-red-900 hover:bg-red-800 text-light rounded text-sm font-medium transition-colors", children: "Delete" })] })] }))] }, card.id)))) })] }));
};
